### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by brandongallagher1999** [GrantBirki/k8s-discord#4]
Hello @GrantBirki ,

I have taken an extensive overview of many of your projects and will be using your structure of /scripts/, a Makefile in root, and using Terraform for provisioning everything in infrastructure (no more kubectl directly) for my work in automation.

Fantastic work. I've learned quite a bit from how you automate the entire end to end cloud process.

**Comment by GrantBirki** [comment]
Fantastic! I'm glad some of my projects were useful to you and I'm super appreciative of the kind words. Thanks!! ❤️
